language: node_js

jobs:
  fast_finish: true
  include:
    - stage: Lint
      env: SCRIPT=lint
      node_js: 'stable'
    - &test
      stage: 'Test'
      env: SCRIPT=test
      node_js: 'stable'
    - <<: *test
      node_js: 'lts/*'
    - <<: *test
      node_js: 6
    - <<: *test
      node_js: 4

script: npm run $SCRIPT

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'

notifications:
  email: false
